### ISSUE TITLE
abaplint.json issue when excluding objects(programs) with namespace in check "names_no_dash"  

### ISSUE THREAD

**Issue by habrahams** [abaplint/abaplint#1226]
I am trying to exclude an object from from the check "names_no_dash" which has a namespace /somenamespace/foobar.prog.abap:

```
"names_no_dash": {
      "exclude": ["#somenamespace#foobar.prog.abap"]
    },
```
Abaplint doesn't process the exclusion, but when I copy the prog.abap and prog.xml file to zfoobar.prog.abap and zfoobar.prog.xml the check excludes the object from the check.
for example:
```
"names_no_dash": {
      "exclude": ["zfoobar.prog.abap"]
    },
```

Also can regular expression be used in the "exclude": [......] statement?

Regards,

**Comment by larshp** [comment]
regular expressions, go to https://rules.abaplint.org/names_no_dash/ and hover the mouse on "excloude" => yes, case insensitive regexes

the "#"'s are actually a problem, when running in vscode the filenames are URIs, which contain "%23" instead of the "#", but I think the command line version keeps the "#"'s, https://github.com/abaplint/abaplint/issues/673

so, I suggest trying 
`"exclude": ["somenamespace[\w#%]+foobar.prog.abap"]`

**Comment by habrahams** [comment]
Thanks @larshp , thank you for the tip! 
The following resolved it for me:
`["[\\w#%]+somenamespace[\\w#%]+foobar.prog.abap"]`

Regards,

**Comment by larshp** [comment]
ah yea, I always forget the escaping
