### ISSUE TITLE
abaplint.app: Skipping abaplint checks for a commit

### ISSUE THREAD

**Issue by mbtools** [abaplint/abaplint#1869]
GH actions can be skipped by appending "[skip ci]" to the commit text. It would be nice if this could be used to skip abaplint runs as well.

**Comment by larshp** [comment]
it would just run on the next commit right? 

just delaying the information/issues found

If some issues are not relevant, suggest disabling the rule, or change the severity.

Also, the user controls in repository configuration, which checks are mandatory for merging a PR

**Comment by mbtools** [comment]
Delaying is the point. one example is changing the rules (commit 1) and fixing objects (commit 2). Or fixing something in multiple commits. If I already know that the lint issues won't be fixed, running the check is just a waste of resources.

**Comment by larshp** [comment]
personally, I'd always like the visibility of showing the results, eg without "real CI" results for "commit 1" there is no visibility for what is exactly to be fixed in "commit 2"

Continuous Integration runs in parallel, results for a second commit should not be delayed due to commit 1. abaplint.app currently has a limited number of workers, but most of the time resources are idle.

Saving resources, yea, but how often? Perhaps saving 1 out of 1000+ commits?

**Comment by mbtools** [comment]
no worry. just an idea to go along with GH standard (https://github.blog/changelog/2021-02-08-github-actions-skip-pull-request-and-push-workflows-with-skip-ci/).

**Comment by larshp** [comment]
there has also been some discussion on github, for how to disable the feature, because some don't want it 😄 

I think the feature might be relevant to deploying, eg if code is automatically deployed at push, some might want to skip. But abaplint is just static analysis...
