### ISSUE TITLE
Transpiling, notes

### ISSUE THREAD

**Issue by larshp** [abaplint/abaplint#792]
Assumption: running the transpiled JS should have the same semantics as running the ABAP code

https://github.com/larshp/ABAPTestSuite

source maps

runtime required

https://adventofcode.com

SQL? Lerna?

**Comment by mrsimpson** [comment]
One aspect not to be forgotten is that - though everything JS - the output may need to be platform specific.
This include different language versions (`node12` vs. `node8`) and may as well need to include polyfills (though this would probably need to be solved at a higher level, so that each statement should not have to be adapted).

I suggest to transform to something compatible to the [lexical analysis of Babel](https://github.com/jamiebuilds/babel-handbook/blob/master/translations/en/plugin-handbook.md#lexical-analysis) so that it can be used in `transform` and `generate`

**Comment by larshp** [comment]
"DATA foo TYPE i." 

-> 

"let foo = new abap.Integer();"
"let foo = new abap.basictypes.i();"
"let foo = new abap.types.basic.i();"

**Comment by larshp** [comment]
the lexer converts the string into tokens, https://github.com/abaplint/abaplint/blob/master/src/abap/lexer.ts

**Comment by larshp** [comment]
see https://github.com/abaplint/transpiler_poc

**Comment by larshp** [comment]
input must be without parser errors or structure errors

some conventions/rules must also be followed, like no EXITs outside loops, in order not to create bad output

**Comment by larshp** [comment]
only accept subset of 702 syntax, rely on the unimplemented downport feature in abaplint

**Comment by mrsimpson** [comment]
Can abaplint be executed with an explicitly very limited white list of allowed statements?

**Comment by larshp** [comment]
no, not really, only by language version

**Comment by larshp** [comment]
https://github.com/babel/babel/blob/master/doc/design/monorepo.md

**Comment by sbcgua** [comment]
@larshp I'm using lerna for some internal stuff. Rather agree with the second link above. `bootstrap` is good: reduces the dependencies, cross-links the submodules together. However: slow, buggy on windows. so quite controversial

**Comment by larshp** [comment]
see https://github.com/abaplint/transpiler
