### ISSUE TITLE
Documentation/examples for CI setups

### ISSUE THREAD

**Issue by larshp** [abaplint/abaplint#823]
add https://github.com/abaplint/actions-abaplint

for gitlab, https://gitlab.com/sbu-absw/abaplint-example/-/merge_requests/8/diffs

**Comment by sbcgua** [comment]
trying some stuff with own actions:
- https://github.com/sbcgua/ci-js-versioning-test/blob/master/action.yml (dont mind the repo name)
- https://github.com/sbcgua/abaplinted_sample/pull/3

Not very successful so far but close. Two questions so far:
1) what are the input parameters for such an action ? I can imagine just pinning abaplint version
2) docker vs ??? - this is also a question. Alternatives are: the docker image (leaner, but breaks from time to time due to huge pivots ;P ) or nodejs ... which kind of more direct but means running the shell commands via node which is not native and means superfluous wiring

P.S. BTW I've updated docker build yesterday evening, should be actual again

**Comment by larshp** [comment]
did you try/take a look at https://github.com/abaplint/actions-abaplint ? pinning version is an open issue, https://github.com/abaplint/actions-abaplint/issues/9

**Comment by sbcgua** [comment]
got back to this. After some head-knocking the wall I realized that I forgot to specify checkout action in the workflow https://github.com/sbcgua/abaplinted_sample/pull/3 ...

But I didn't figure out how to make action use specific docker image version. So it seems that there is no advantage in an action based on docker, hmmm :(

**Comment by larshp** [comment]
just use https://github.com/abaplint/actions-abaplint ? might do some more work on it today

ci documentation setup: would like to move it to http://docs.abaplint.org, maybe a Jekyll setup would be nice, maybe move the files to /web/docs

**Comment by larshp** [comment]
doing some work on this now

**Comment by larshp** [comment]
done? closing
