### ISSUE TITLE
rules.abaplint.org ideas and todo

### ISSUE THREAD

**Issue by larshp** [abaplint/abaplint#827]
+ use jekyll?
+ show and edit full default configuration
+ editor for good and bad examples

**Comment by flaiker** [comment]
- Scale the svg icons correctly in firefox? ;)

![image](https://user-images.githubusercontent.com/5270359/80303942-86e0da00-87b3-11ea-960f-148bfa9d2563.png)

**Comment by larshp** [comment]
heh, I'll take a look

**Comment by larshp** [comment]
no problems in v.75,

![image](https://user-images.githubusercontent.com/5888506/80304365-93fec880-87b5-11ea-90fc-a8fb947480ec.png)

**Comment by flaiker** [comment]
Seems like I am on the ESR release channel. I only noticed because I recently got firefox pushed as the default browser by group policy, causing the vscode links open using it.

![image](https://user-images.githubusercontent.com/5270359/80304459-3e76eb80-87b6-11ea-9400-538300945fc1.png)

Feel free to ignore then I guess

**Comment by larshp** [comment]
also feel free to submit fix, I wont look more into it

**Comment by larshp** [comment]
closing this, opening specifc issues instead
